### PR TITLE
Add --version and --help arguments

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by maralorn** [comment]
Nice! I would have considered using something like optparse-applicative. You decided it's not worth the hazzle?

**Comment by maralorn** [comment]
btw, what I meant with legend and explanation, were three lines of the form

"<icon>, blue, in Queue"
"<icon>, yellow, running"
"<icon>, green, completed"

so that users understand the output better after looking at the help text.

But I can add that later.

**Comment by expipiplus1** [comment]
Yeah, for anything more complex than this then optparse-a is definitely
better. Forgot about the legend, but hopefully this is still an
improvement.

**Comment by maralorn** [comment]
Yeah, definitely an improvement! Thank you!

**Pull request merged**
