### PR TITLE
feat: add bash completion

### PR DESCRIPTION
**Pull request by pdietl**
Makes fixes to #123

### CODE REVIEW

**Comment by maralorn** [comment]
Awesome! Will review, when I find the time.

**Comment by pdietl** [comment]
Yeah take your time. This makes completion work for the argument possibilities to `nom` itself plus arguments to the underlying `nix` commands. I used `Process.runProcess` to avoid the printing of the "Finished ..." message.

**Comment by pdietl** [comment]
@tomberek what do you think?

**Review by tomberek — APPROVED** [review]
Works for me!

**Comment by maralorn** [comment]
I have built on your commit, refactored a bit and added `nom` completion for zsh as well. Thank you. 

(This PR didn’t get auto-closed because I rebased your commit.)

Thanks to you both. :heart:

**Comment by philiptaron** [comment]
I've wanted this for so long. Thank you so much @pdietl, @tomberek, and @maralorn!

**Comment by pdietl** [comment]
@philiptaron you're most welcome.

**Pull request closed without merging**
