### PR TITLE
Add support for activity type 112

### PR DESCRIPTION
**Pull request by maralorn**

### CODE REVIEW

**Comment by Mic92** [comment]
Can we get a release please?

**Comment by maralorn** [comment]
Sure, will get to it within a week.

**Comment by shymega** [comment]
@maralorn Did a release get made? I'm hitting the `DocumentError` lately.

**Comment by maralorn** [comment]
@shymega The fix should have reached nixos-unstable but nixos-stable.

**Comment by shymega** [comment]
@maralorn Ah yes. I was not looking at `git ls-remote --tags`, but instead GitHub releases.

I think I've found a new regression, but I'll do some testing on unstable.

**Pull request merged**
